POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "joanpurba562@gmail.com",
  "username": "joan",
  "password": "121206"
}

###
POST http://localhost:3000/signup
Content-Type: application/json

{
  "email": "joanpurba562@gmail.com",
  "username": "joan",
  "password": "121206"
}

###
GET http://localhost:3000/show
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzJkNzY3YmZlYjVlNjdkYTFmYTA4MiIsImVtYWlsIjoiam9hbkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImpvYW4iLCJpYXQiOjE3MjQxNjQ5NjAsImV4cCI6MTcyNDE2NDk3NX0.7FFlRTstcXVLFN89mVlrUVEL-fyEIyqapdOTmFX5UB4

###
GET http://localhost:3000/token

###
GET http://localhost:3000/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzJkNzY3YmZlYjVlNjdkYTFmYTA4MiIsImVtYWlsIjoiam9hbkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImpvYW4iLCJpYXQiOjE3MjQxNjk3MzksImV4cCI6MTcyNDE2OTc1NH0.lOnTVNVUjZdvPPtcy7H9EszNRdZSbw9kdrePbLZlCwQ

###
GET http://localhost:3000/showbyid/66c46f25a3f9826cee75cba8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YzQ2ZjI1YTNmOTgyNmNlZTc1Y2JhOCIsImVtYWlsIjoicmFkaXRAZ21haWwuY29tIiwidXNlcm5hbWUiOiJyYWRpdCIsImlhdCI6MTcyNDMzMjM3NiwiZXhwIjoxNzI0MzMyMzkxfQ.vgBAPsd0-4TITxcGjUVDAosHGCpY9_VgFHMmN7rc9Vw

###
POST http://localhost:3000/logout
Content-Type: application/json

{
  "id" : "66d0696898852c80de418166"
}

###
POST http://localhost:3000/sendotp
Content-Type: application/json

###
DELETE http://localhost:3000/deleteallposts